local M = {}

-- Declarative public API surface.
--
-- `exports.lua` reads this table to install lazy wrappers and classify stable
-- versus experimental symbols, so adding a method here exposes it to users.
M.stable_root_functions = {
    "setup",
    "api_version",
    "capabilities",
    "version",
    "contract",
    "public_symbols",
    "stable_symbols",
    "experimental_symbols",
    "is_setup",
}

-- Namespace tiers document the ownership contract for the installed Lua API.
-- "mixed" namespaces expose a small explicit stable subset below; every other
-- installed symbol in those namespaces is still experimental until promoted.
M.namespace_tiers = {
    project = "mixed",
    compiler = "mixed",
    viewer = "mixed",
    artifact = "experimental",
    diagnostics = "experimental",
    development = "experimental",
    evaluation = "experimental",
    invalidation = "experimental",
    render = "experimental",
    semantic = "experimental",
    template = "experimental",
    tools = "experimental",
    ui = "experimental",
    conceal = "experimental",
    bibliography = "experimental",
    completion = "experimental",
    picker = "experimental",
    navigation = "experimental",
    context = "experimental",
    package = "experimental",
    symbol = "experimental",
    metadata = "experimental",
    providers = "experimental",
    index = "experimental",
    syntax = "experimental",
    imaps = "experimental",
    match_highlight = "experimental",
    edit = "experimental",
}

M.internal_module_prefixes = {
    "typst.core.",
    "typst.project.registry",
    "typst.project.store",
    "typst.project.services.",
    "typst.resources.",
    "typst.runtime.",
    "typst.internal.",
}

M.stable_namespaces = {}

M.stable_runtime_symbols = {
    "compiler.compile",
    "compiler.compile_selected",
    "compiler.current_output",
    "compiler.output",
    "compiler.status",
    "compiler.stop",
    "compiler.stop_all",
    "compiler.watch",
    "project.attach",
    "project.cd",
    "project.clear_cache",
    "project.detach",
    "project.edit_main",
    "project.get",
    "project.projects",
    "project.reload_state",
    "project.set_main",
    "project.snapshot",
    "project.toggle_main",
    "viewer.capabilities",
    "viewer.view",
    "viewer.view_forward",
    "viewer.view_inverse",
}

local edit_methods = {
    "next_heading",
    "previous_heading",
    "next_heading_end",
    "previous_heading_end",
    "next_block",
    "previous_block",
    "next_block_end",
    "previous_block_end",
    "next_equation",
    "previous_equation",
    "next_equation_end",
    "previous_equation_end",
    "next_raw_block",
    "previous_raw_block",
    "next_comment",
    "previous_comment",
    "match",
    "select_textobject",
    "structural_action",
    "promote_heading",
    "demote_heading",
    "refresh_folds",
    "unwrap_function",
    "change_function",
    "change_delimiter",
    "change_delimiter_content",
    "change_delimiter_block",
    "change_delimiter_group",
    "change_delimiter_equation",
    "split_arguments",
    "join_arguments",
    "toggle_arguments",
    "name_arguments",
    "toggle_trailing_comma",
    "add_trailing_comma",
    "remove_trailing_comma",
    "toggle_label",
    "toggle_reference",
    "toggle_label_reference",
    "surround",
    "surround_function",
    "surround_content",
    "surround_equation",
    "surround_figure",
    "surround_block",
    "surround_strong",
    "surround_emph",
    "surround_delete_call",
    "surround_change_call",
    "surround_delete_delimiter",
    "surround_change_delimiter",
    "surround_delete_block",
    "surround_change_block",
    "surround_delete_equation",
    "surround_change_equation",
    "insert",
    "insert_strong",
    "insert_emph",
    "insert_math",
    "insert_content",
    "insert_code",
    "insert_raw",
    "toggle_markup",
    "toggle_strong",
    "toggle_emph",
    "toggle_figure",
    "toggle_list",
    "toggle_bullet_list",
    "toggle_numbered_list",
    "convert_equation",
    "toggle_equation_numbering",
    "toggle_fraction",
    "toggle_delimiter_size",
    "toggle_line_break",
    "create_function",
    "smart_close",
    "convert_raw",
}

M.namespaces = {
    {
        name = "project",
        source = {
            type = "factory",
            module = "typst.project.api",
            method = "create",
        },
        methods = {
            attach = "attach",
            detach = "detach",
            get = "get_project",
            snapshot = "snapshot",
            projects = "projects",
            set_main = "set_main",
            toggle_main = "toggle_main",
            edit_main = "edit_main",
            cd = "cd",
            reload_state = "reload_state",
            clear_cache = "clear_cache",
            on_invalidate = {
                module = "typst.project.invalidation",
                method = "subscribe",
            },
            invalidate = {
                module = "typst.project.invalidation",
                method = "emit",
            },
            invalidation_snapshot = {
                module = "typst.project.invalidation",
                method = "snapshot",
            },
        },
    },
    {
        name = "invalidation",
        source = { module = "typst.project.invalidation" },
        methods = {
            subscribe = "subscribe",
            emit = "emit",
            emit_reason = "emit_reason",
            generation = "generation",
            snapshot = "snapshot",
        },
    },
    {
        name = "conceal",
        source = { module = "typst.conceal" },
        methods = {
            enable = "enable",
            disable = "disable",
            toggle = "toggle",
            refresh = "refresh",
            inspect = "inspect",
            is_enabled = "is_enabled",
            register = "register",
            unregister = "unregister",
            custom = "custom",
        },
    },
    {
        name = "bibliography",
        source = { module = "typst.bibliography" },
        methods = {
            diagnostics = "diagnostics",
            clear_diagnostics = "clear_diagnostics",
            diagnostics_namespace = {
                custom = "bibliography_diagnostics_namespace",
            },
            foldexpr = "foldexpr",
            indentexpr = "indentexpr",
            fields = "fields",
            expanded_fields = "expanded_fields",
            search = "search",
            insert_text = "insert_text",
            insert = "insert",
            open = "open",
            preview = "preview",
            attachment = "attachment",
            attachments = "attachments",
            rename_plan = "rename_plan",
            rename_key = "rename_key",
            status = "status",
            parse_bibtex_file = "parse_bibtex_file",
            parse_hayagriva_file = "parse_hayagriva_file",
        },
    },
    {
        name = "completion",
        source = { module = "typst.completion" },
        methods = {
            complete = "complete",
            native = "native",
            cmp = "cmp",
            blink = "blink",
            cmp_source = "cmp_source",
            blink_source = "blink_source",
            omnifunc = "omnifunc",
            signature = "signature",
        },
    },
    {
        name = "picker",
        source = { module = "typst.navigation.picker" },
        methods = {
            items = "items",
            open = "open",
            pick = "open",
            open_item = "open_item",
        },
    },
    {
        name = "navigation",
        methods = {
            follow = {
                module = "typst.navigation.follow",
                method = "follow",
            },
            pick = {
                module = "typst.navigation.picker",
                method = "open",
            },
            pick_items = {
                module = "typst.navigation.picker",
                method = "items",
            },
        },
    },
    {
        name = "context",
        source = { module = "typst.context" },
        methods = {
            open = "open",
        },
    },
    {
        name = "package",
        source = { module = "typst.package" },
        methods = {
            info = "info",
            open = "open",
            readme = "readme",
            source = "source",
            lookup = "lookup",
            cached_packages = "cached_packages",
            prewarm = "prewarm",
        },
    },
    {
        name = "symbol",
        source = { module = "typst.metadata.symbol" },
        methods = {
            info = "info",
            variants = "variant_info",
            search = "search",
            lookup = "lookup",
        },
    },
    {
        name = "metadata",
        source = { module = "typst.metadata" },
        methods = {
            available_versions = "available_versions",
            catalog = "catalog",
            stdlib = "stdlib",
            stdlib_item = "stdlib_item",
            stdlib_complete = "stdlib_complete",
            stdlib_param_docs = "stdlib_param_docs",
            stdlib_constants_by_type = "stdlib_constants_by_type",
            signature = "signature",
            shorthands = "shorthands",
            symbol = "symbol",
            symbol_glyph = "symbol_glyph",
            symbol_variants = "symbol_variants",
            symbol_deprecation = "symbol_deprecation",
            symbol_names = "symbol_names",
            emoji = "emoji",
            emoji_glyph = "emoji_glyph",
            emoji_variants = "emoji_variants",
            emoji_names = "emoji_names",
            emojis = "emojis",
        },
    },
    {
        name = "providers",
        source = { module = "typst.integrations.providers" },
        methods = {
            register = "register",
            unregister = "unregister",
            get = "get",
            has = "has",
            names = "names",
        },
    },
    {
        name = "index",
        source = { module = "typst.index" },
        methods = {
            headings = "headings",
            labels = "labels",
            citations = "citations",
            imports = "imports",
            todos = "todos",
            definitions = "definitions",
            glossary_entries = "glossary_entries",
            paths = "paths",
            collect = "collect",
            mark_dirty = "mark_dirty",
            reset = "reset",
        },
    },
    {
        name = "syntax",
        source = { module = "typst.syntax" },
        methods = {
            package_extensions = "package_extensions",
            package_matches = "package_matches",
            refresh = "refresh",
            clear = "clear",
            namespace = "namespace",
        },
    },
    {
        name = "imaps",
        source = { module = "typst.edit.imaps" },
        methods = {
            register = "register",
            unregister = "unregister",
            active = "active",
            list = "list",
            lines = "lines",
        },
    },
    {
        name = "match_highlight",
        source = { module = "typst.edit.match_highlight" },
        methods = {
            enable = "enable",
            disable = "disable",
            toggle = "toggle",
            refresh = "refresh",
            is_enabled = "is_enabled",
        },
    },
    {
        name = "edit",
        source = {
            type = "factory",
            module = "typst.edit.api",
            method = "create",
        },
        methods = edit_methods,
    },
}

M.globals = {
    {
        name = "typst_nvim_omnifunc",
        module = "typst.completion",
        method = "omnifunc",
    },
    {
        name = "typst_nvim_indentexpr",
        module = "typst.edit.indent",
        method = "indent",
    },
    {
        name = "typst_nvim_formatexpr",
        module = "typst.edit.formatexpr",
        method = "formatexpr",
        args = "formatexpr",
    },
    {
        name = "typst_nvim_foldexpr",
        module = "typst.edit.folds",
        method = "expr",
        args = "foldexpr",
    },
    {
        name = "typst_nvim_foldtext",
        module = "typst.edit.folds",
        method = "foldtext",
    },
}

return M
