local M = {}

local function set_from_list(values)
    local out = {}
    for _, value in ipairs(values or {}) do
        out[value] = true
    end
    return out
end

-- Paths whose values are intentionally open-ended maps. Unknown-key validation
-- must not recurse into these unless a dedicated validator below handles the
-- dynamic section.
M.dynamic_paths = set_from_list({
    "api",
    "conceal.custom",
    "conceal.reveal_by_category",
    "main",
    "compile.profiles",
    "compile.fragments.templates",
    "exports.profiles",
    "imaps.mappings",
    "integrations.tinymist.capabilities",
    "integrations.tinymist.init_options",
    "integrations.tinymist.settings",
    "preview.browser.style.variables",
    "syntax.packages",
    "viewer.providers",
})

-- Optional paths that are valid even when runtime defaults omit the key or set
-- it indirectly through provider-specific defaults.
M.optional_paths = set_from_list({
    "main",
    "metadata_version",
    "main_base_dir",
    "output_name",
    "root",
    "project.import_scan_max_descendant_depth",
    "compile.fragments.source_dir",
    "compile.generic.compile",
    "compile.generic.cwd",
    "compile.generic.output",
    "compile.generic.watch",
    "compile.provider",
    "compile.task.compile",
    "compile.task.cwd",
    "compile.task.output",
    "compile.task.watch",
    "conceal.reveal_insert",
    "exports.default",
    "exports.provider",
    "folds.text",
    "grammar.command",
    "grammar.file_arg",
    "grammar.stdin",
    "integrations.tinymist.capabilities",
    "integrations.tinymist.cmd",
    "integrations.tinymist.on_attach",
    "lint.command",
    "log.file_path",
    "picker.custom",
    "preview.browser.app",
    "preview.browser.commands",
    "preview.browser.export.output_dir",
    "preview.browser.export.output_format",
    "preview.browser.export.output_name",
    "preview.browser.export.profile",
    "preview.browser.export.provider",
    "preview.browser.open",
    "preview.browser.style.css",
    "preview.browser.style.css_path",
    "preview.export.output_dir",
    "preview.export.output_format",
    "preview.export.output_name",
    "preview.export.profile",
    "preview.export.provider",
    "preview.forward",
    "preview.inverse",
    "preview.open",
    "preview.refresh",
    "preview.source_maps.forward",
    "preview.source_maps.inverse",
    "preview.stop",
    "render.display_provider",
    "render.provider",
    "viewer.forward",
    "viewer.inverse",
    "viewer.open",
    "viewer.reload",
})

-- Optional nil-valued paths that should appear in generated config docs even
-- when defaults do not materialize the key.
M.doc_nil_defaults = {
    "metadata_version",
    "main_base_dir",
    "output_name",
    "root",
    "main",
    "project.import_scan_max_descendant_depth",
    "compile.provider",
    "exports.provider",
    "exports.default",
    "format.command",
    "grammar.command",
    "grammar.stdin",
    "grammar.file_arg",
    "integrations.tinymist.cmd",
    "integrations.tinymist.capabilities",
    "integrations.tinymist.on_attach",
    "lint.command",
    "log.file_path",
    "picker.custom",
    "render.provider",
    "render.display_provider",
    "viewer.open",
    "viewer.reload",
    "viewer.forward",
    "viewer.inverse",
    "preview.browser.export.output_dir",
    "preview.browser.export.output_format",
    "preview.browser.export.output_name",
    "preview.browser.export.profile",
    "preview.browser.export.provider",
    "preview.browser.app",
    "preview.browser.commands",
    "preview.browser.open",
    "preview.browser.style.css",
    "preview.browser.style.css_path",
    "preview.export.output_dir",
    "preview.export.output_format",
    "preview.export.output_name",
    "preview.export.profile",
    "preview.export.provider",
    "preview.open",
    "preview.stop",
    "preview.refresh",
    "preview.forward",
    "preview.inverse",
    "preview.source_maps.provider",
    "preview.source_maps.forward",
    "preview.source_maps.inverse",
    "folds.text",
}

M.doc_optional_types = {
    ["integrations.tinymist.capabilities"] = "nil|table",
    ["integrations.tinymist.on_attach"] = "nil|function",
    ["log.file_path"] = "nil|string",
    main_base_dir = "nil|string",
    ["integrations.semantic.provider"] = "nil|string|function|table",
    ["compile.provider"] = "nil|string|function|table",
    ["exports.provider"] = "nil|string|function|table",
    ["render.provider"] = "nil|string|function|table",
    ["render.display_provider"] = "nil|string|function|table",
    ["viewer.open"] = "nil|string|function",
    ["viewer.reload"] = "nil|string|function",
    ["viewer.forward"] = "nil|string|function",
    ["viewer.inverse"] = "nil|string|function",
    ["preview.browser.export.output_dir"] = "nil|string",
    ["preview.browser.export.output_format"] = "nil|string",
    ["preview.browser.export.output_name"] = "nil|string",
    ["preview.browser.export.profile"] = "nil|string",
    ["preview.browser.export.provider"] = "nil|string|function|table",
    ["preview.browser.app"] = "nil|string",
    ["preview.browser.commands"] = "nil|list",
    ["preview.browser.open"] = "nil|function",
    ["preview.browser.style.css"] = "nil|string",
    ["preview.browser.style.css_path"] = "nil|string",
    ["preview.export.output_dir"] = "nil|string",
    ["preview.export.output_format"] = "nil|string",
    ["preview.export.output_name"] = "nil|string",
    ["preview.export.profile"] = "nil|string",
    ["preview.export.provider"] = "nil|string|function|table",
    ["preview.open"] = "nil|function",
    ["preview.stop"] = "nil|function",
    ["preview.refresh"] = "nil|function",
    ["preview.forward"] = "nil|function",
    ["preview.inverse"] = "nil|function",
    ["preview.source_maps.provider"] = "nil|string|function|table",
    ["preview.source_maps.forward"] = "nil|function",
    ["preview.source_maps.inverse"] = "nil|function",
    ["project.import_scan_max_descendant_depth"] = "nil|number",
    ["folds.text"] = "nil|string|function",
}

M.doc_type_overrides = {
    ["diagnostics.external_paths"] = "string",
    ["diagnostics.max_external_buffers"] = "integer",
    ["diagnostics.overflow"] = "string",
    ["integrations.semantic.provider"] = "nil|string|function|table",
    ["preview.browser.style.variables"] = "table",
    validation = "false|string",
}

M.export_profile_fields = {
    "command",
    "compile_format",
    "creation_timestamp",
    "cwd",
    "diagnostic_format",
    "extra_args",
    "features",
    "font_path",
    "font_paths",
    "format",
    "ignore_embedded_fonts",
    "ignore_system_fonts",
    "input",
    "inputs",
    "jobs",
    "name",
    "no_pdf_tags",
    "output_dir",
    "output_format",
    "output_name",
    "package_cache_path",
    "package_path",
    "pages",
    "pdf_standard",
    "pdf_standards",
    "ppi",
    "pretty",
    "provider",
    "stdout",
    "timings",
    "typst_format",
}

M.export_profile_allowed = set_from_list(M.export_profile_fields)

return M
