---@meta typst.types

---@class TypstProject
---@field key string Stable registry key built from root and main.
---@field instance_id integer Session-local project object identity used to reject stale public snapshots.
---@field root string Normalized project root path.
---@field main string Normalized Typst main file path.
---@field services TypstProjectServices Per-project service tables.
---@field bufs table<integer, true> Attached buffers.
---@field resolutions table<integer, table> Per-buffer resolution metadata.
---@field last_resolution table? Last project resolution metadata.
---@field root_source string? Source that selected `root`.
---@field main_source string? Source that selected `main`.
---@field main_confidence '"high"'|'"medium"'|'"low"'? Confidence of main resolution.
---@field main_confidence_source string? Original source used for confidence.
---@field resolution_pending '"import_scan"'? Deferred resolver stage still running.
---@field compiler_provider TypstProviderBinding? Active compiler binding.
---@field _typst_project_pruned boolean? Registry prune marker used during detach.
---@field _typst_project_pruned_reason string? Reason recorded when pruned.
---@field _typst_project_pruned_event_emitted boolean? Project-pruned event guard.
---@field [string] any

---@class TypstCompilerResult
---@field ok boolean?
---@field code integer? Process/operation exit code when available.
---@field stdout string?
---@field stderr string?
---@field output string?
---@field path string?
---@field artifacts table[]?
---@field outputs table[]?
---@field diagnostics table?
---@field by_buffer table<integer, table[]>?
---@field stale boolean? Result was superseded by a newer run.
---@field stopped boolean? Operation reached a stop transition.
---@field idle boolean? Stop was requested while no process/watcher was active.
---@field forced boolean? Stop required forced termination.
---@field orphaned boolean? Process could not be confirmed stopped.
---@field watch boolean? Result belongs to a watch cycle or watcher.
---@field cycle integer? Watch cycle number.
---@field generation integer? Compiler generation.
---@field watch_generation integer? Watcher generation.
---@field cycle_generation integer? Watch cycle generation.
---@field reason string?
---@field message string?
---@field error string?
---@field active_output string?
---@field deps_path string?
---@field profile string?
---@field watch_status string?
---@field last_cycle_status string?
---@field external_lock boolean?
---@field [string] any

---@class TypstProviderResult
---@field ok boolean?
---@field reason string?
---@field provider string?
---@field error string?
---@field message string?
---@field client string?
---@field method string?
---@field pending boolean?
---@field cancel_pending boolean? A cancel request is still settling with the provider.
---@field stopped boolean?
---@field forced boolean?
---@field orphaned boolean?
---@field stale boolean?
---@field [string] any

---@class typst.ProviderResult: TypstProviderResult

---@class TypstProviderPendingHandle
---@field pending true
---@field ok boolean?
---@field reason string?
---@field provider string?
---@field message string?
---@field error string?
---@field handle any?
---@field cancel? fun(self_or_opts: TypstProviderPendingHandle|table?, opts?:table):boolean, TypstProviderResult?
---@field stop? fun(self_or_opts: TypstProviderPendingHandle|table?, opts?:table):boolean, TypstProviderResult?
---@field kill? fun(self_or_opts: TypstProviderPendingHandle|table?, opts?:table):boolean, TypstProviderResult?
---@field [string] any

---@class typst.ProviderCancelHandle: TypstProviderPendingHandle

---@class TypstProviderContext
---@field key string?
---@field root string?
---@field main string?
---@field path string?
---@field bufnr integer?
---@field output string?
---@field profile string?
---@field services TypstProjectServices?
---@field last_command string[]?
---@field last_cwd string?
---@field [string] any

---@class TypstProviderInvokeControl
---@field kind string?
---@field provider_name string?
---@field callback_position integer?
---@field callback_name string?
---@field timeout_ms integer?
---@field async boolean?
---@field return_mode '"result"'|'"handle"'?
---@field accept_table_result boolean?
---@field result_fields table<string, boolean>?
---@field normalize? fun(raw:any, provider_name:string):TypstProviderResult|table
---@field is_handle? fun(result:any):boolean
---@field callback? fun(result:TypstProviderResult|table, context?:TypstProviderContext)
---@field invalid_result_message string?

---@class TypstCompilerRunConfig
---@field profile string?
---@field output_dir string?
---@field output_name string?
---@field output_format string?
---@field extra_args string[]?
---@field cwd string?
---@field open boolean?
---@field typst_open boolean?

---@class TypstProviderBinding
---@field provider table
---@field builtin boolean
---@field external boolean
---@field name string?

---@class TypstCompileProvider
---@field compile fun(project:TypstProject|TypstProviderContext|table, callback?:fun(result:TypstCompilerResult), run_config?:TypstCompilerRunConfig|table):TypstProviderPendingHandle|TypstCompilerResult|unknown
---@field start fun(project:TypstProject|TypstProviderContext|table, callback?:fun(result:TypstCompilerResult), run_config?:TypstCompilerRunConfig|table):TypstProviderPendingHandle|TypstCompilerResult|unknown
---@field stop fun(project:TypstProject|TypstProviderContext|table, callback?:fun(result:TypstCompilerResult)):TypstProviderPendingHandle|TypstCompilerResult|unknown
---@field stop_for_exit? fun(project:TypstProject|TypstProviderContext|table, opts?:table):TypstProviderPendingHandle|TypstCompilerResult|unknown
---@field status fun(project:TypstProject|table):string?
---@field output? fun(project:TypstProject|TypstProviderContext|table, run_config?:TypstCompilerRunConfig|table):string?
---@field outputless? boolean
---@field name string?

---@class TypstProjectServices
---@field operations TypstProjectOperationsService?
---@field compiler TypstProjectCompilerService?
---@field diagnostics TypstProjectDiagnosticsService?
---@field preview TypstProjectPreviewService?
---@field artifacts TypstProjectArtifactsService?
---@field graph TypstProjectGraphService?
---@field index TypstProjectIndexService?
---@field viewer TypstProjectViewerService?
---@field invalidation TypstProjectInvalidationService?
---@field integrations TypstProjectIntegrationsService?
---@field lifecycle TypstProjectLifecycleService?

---@class TypstProjectServicePatch
---@field clear string[]?
---@field _clear string[]?

---@class TypstProjectIntegrationsService
---@field tinymist table?
---@field [string] any

---@class TypstProjectIntegrationsServicePatch: TypstProjectServicePatch
---@field tinymist table?
---@field [string] any

---@class TypstProjectLifecycleService
---@field last_transition TypstProjectTransition?
---@field last_reload_cache table<string, boolean>?
---@field [string] any

---@class TypstProjectLifecycleServicePatch: TypstProjectServicePatch
---@field last_transition TypstProjectTransition?
---@field last_reload_cache table<string, boolean>?
---@field [string] any

---@class TypstProjectTransition
---@field ok boolean
---@field previous_stop_requested boolean?
---@field emitted_events boolean?
---@field finalization_error string?
---@field reason string?
---@field bufnr integer?
---@field previous_key string?
---@field project_key string?

---@class TypstProjectOperationRecord
---@field id integer
---@field kind string
---@field generation integer
---@field started_at integer
---@field finished boolean?
---@field retained_at integer?
---@field handle any?
---@field result table?
---@field [string] any

---@class TypstProjectOperationsService
---@field active_by_id table<integer, TypstProjectOperationRecord>
---@field active_by_kind table<string, table<integer, true>>
---@field retained_by_id table<integer, TypstProjectOperationRecord>
---@field retained_by_kind table<string, table<integer, true>>
---@field generations table<string, integer>
---@field last table<string, table>
---@field next_id integer
---@field [string] any

---@class TypstProjectCompilerService
---@field status string
---@field generation integer
---@field watch_generation integer
---@field watch_cycle_generation integer
---@field output string?
---@field output_lease table?
---@field process any?
---@field watcher TypstCompilerWatcher?
---@field process_operation table?
---@field watcher_operation table?
---@field stopping_compile table?
---@field last_result TypstCompilerResult?
---@field last_profile string?
---@field last_cwd string?
---@field watch_cycle integer?
---@field watch_cycle_status string?
---@field last_cycle_generation integer?
---@field active_compile_deps_path string?
---@field restart_handle table?
---@field stop_for_exit boolean?
---@field provider_label string?
---@field last_provider_label string?
---@field provider_builtin boolean?
---@field provider_external boolean?
---@field [string] any

---@class TypstCompilerState: TypstProjectCompilerService

---@class TypstProjectCompilerServicePatch: TypstProjectServicePatch
---@field status string?
---@field generation integer?
---@field watch_generation integer?
---@field watch_cycle_generation integer?
---@field output string?
---@field output_lease table?
---@field process any?
---@field watcher TypstCompilerWatcher?
---@field process_operation table?
---@field watcher_operation table?
---@field stopping_compile table?
---@field last_result TypstCompilerResult?
---@field last_profile string?
---@field last_cwd string?
---@field watch_cycle integer?
---@field watch_cycle_status string?
---@field last_cycle_generation integer?
---@field [string] any

---@class TypstProjectDiagnosticsService
---@field buffers table<integer, true>
---@field last table?
---@field [string] any

---@class TypstProjectDiagnosticsServicePatch: TypstProjectServicePatch
---@field buffers table<integer, true>?
---@field last table?
---@field [string] any

---@class TypstProjectPreviewService
---@field active boolean
---@field active_backend string?
---@field active_mode string?
---@field active_url string?
---@field active_output string?
---@field active_export table?
---@field active_transport string?
---@field active_shell string?
---@field active_server_port integer?
---@field active_command string[]?
---@field active_cwd string?
---@field last_backend string?
---@field last_url string?
---@field last_output string?
---@field last_export table?
---@field last_command string[]?
---@field last_cwd string?
---@field last_error table?
---@field last_result table?
---@field stop_prune_reason string?
---@field stopping boolean?
---@field status string?
---@field opening boolean?
---@field open_handle table?
---@field open_generation integer?
---@field last_mode string?
---@field retained_open_handles table[]?
---@field [string] any

---@class TypstProjectPreviewServicePatch: TypstProjectServicePatch
---@field active boolean?
---@field active_backend string?
---@field active_mode string?
---@field active_url string?
---@field active_output string?
---@field active_export table?
---@field active_transport string?
---@field active_shell string?
---@field active_server_port integer?
---@field active_command string[]?
---@field active_cwd string?
---@field last_backend string?
---@field last_url string?
---@field last_output string?
---@field last_export table?
---@field last_command string[]?
---@field last_cwd string?
---@field last_error table?
---@field last_result table?
---@field stop_prune_reason string?
---@field stopping boolean?
---@field status string?
---@field opening boolean?
---@field open_handle table?
---@field open_generation integer?
---@field last_mode string?
---@field retained_open_handles table[]?
---@field [string] any

---@class TypstProjectArtifactsService
---@field items table[]
---@field owned table?
---@field output string?
---@field last table?
---@field [string] any

---@class TypstProjectArtifactsServicePatch: TypstProjectServicePatch
---@field items table[]?
---@field owned table?
---@field output string?
---@field last table?
---@field [string] any

---@class TypstProjectGraphService
---@field files table<string, table|boolean>
---@field file_sources table<string, string>
---@field dependencies table<string, table|boolean>
---@field dependency_sources table<string, string>
---@field [string] any

---@class TypstProjectGraphServicePatch: TypstProjectServicePatch
---@field files table<string, table|boolean>?
---@field file_sources table<string, string>?
---@field dependencies table<string, table|boolean>?
---@field dependency_sources table<string, string>?
---@field [string] any

---@class TypstProjectIndexService
---@field files table<string, table>
---@field bibliographies table<string, table>
---@field graph table
---@field generation integer?
---@field dirty_reason string?
---@field [string] any

---@class TypstProjectViewerService
---@field provider string?
---@field backend string?
---@field command string[]?
---@field cwd string?
---@field stats table?
---@field [string] any

---@class TypstProjectViewerServicePatch: TypstProjectServicePatch
---@field provider string?
---@field backend string?
---@field command string[]?
---@field cwd string?
---@field stats table?
---@field [string] any

---@class TypstProjectInvalidationService
---@field generation integer
---@field counters table<string, integer>
---@field subscribers table
---@field history table
---@field last table?
---@field [string] any

---@class TypstProjectInvalidationServicePatch: TypstProjectServicePatch
---@field generation integer?
---@field counters table<string, integer>?
---@field subscribers table?
---@field history table?
---@field last table?
---@field [string] any

---@class TypstWatchCycle
---@field id integer
---@field generation integer
---@field stdout string
---@field stderr string
---@field started_at integer
---@field finished boolean
---@field finish_timer userdata?
---@field pending_error_reason string?
---@field [string] any

---@class TypstWatchRestart
---@field callback fun(result:TypstCompilerResult)?
---@field opts table?
---@field run_config TypstCompilerRunConfig|table?
---@field restart_handle table?

---@class TypstWatchStreamChunk
---@field stream '"stdout"'|'"stderr"'
---@field data string

---@class TypstCompilerWatcher
---@field handle any
---@field operation table?
---@field generation integer
---@field cycle integer?
---@field cycle_generation integer?
---@field current_cycle TypstWatchCycle?
---@field callback fun(result:TypstCompilerResult)?
---@field output string?
---@field deps_path string?
---@field deps_signature string?
---@field stopping boolean?
---@field restart_handle table?
---@field exit_cleanup boolean?
---@field stop_callbacks fun(result:TypstCompilerResult)[]?
---@field restart_pending TypstWatchRestart?
---@field kill_timer userdata?
---@field stdout string?
---@field stderr string?
---@field line_buffers table<string, string>?
---@field stream_queue TypstWatchStreamChunk[]?
---@field stream_queue_scheduled boolean?
---@field stream_queue_bytes integer?
---@field stream_queue_chunks integer?
---@field stream_queue_truncated boolean?
---@field stream_queue_dropped_chunks integer?
---@field stream_queue_dropped_bytes integer?
---@field last_stream_truncation_warning_at integer?
---@field last_cycle_id integer?
---@field last_cycle_generation integer?
---@field last_cycle_status string?
---@field currently_compiling boolean?
---@field watch_output string?
---@field watch_output_wait_ms integer?
---@field watch_structured_args string[]?
---@field typst_version string?
---@field structured_output_seen boolean?
---@field unrecognized_status_lines integer?
---@field last_unrecognized_status_line string?
---@field [string] any

---@class TypstStoppingCompile
---@field handle any
---@field callbacks fun(result:TypstCompilerResult)[]
---@field deps_path string?
---@field kill_timer userdata?
---@field finished boolean?
---@field exit_cleanup boolean?

---@class TypstCompletionContext
---@field bufnr integer
---@field line string?
---@field col integer?
---@field cursor integer[]?
---@field mode string?
---@field syntax string?
---@field path string?
---@field project TypstProject?

---@class TypstCompletionItem
---@field word string
---@field abbr string?
---@field menu string?
---@field kind string?
---@field info string?
---@field dup integer?
---@field icase integer?
---@field user_data table?

---@class TypstCompletionOptions
---@field bufnr integer?
---@field base string?
---@field context TypstCompletionContext|table?
---@field limit integer?
---@field include_tinymist boolean?
---@field completion_session string?
---@field on_tinymist_results fun(items:TypstCompletionItem[])?

---@class TypstCompletionSource
---@field is_available? fun():boolean
---@field get_trigger_characters? fun():string[]
---@field complete? fun(self:any, params:table, callback:fun(result:table))
---@field get_completions? fun(self:any, params:table, callback:fun(result:table))

---@class TypstCacheRegistryStats
---@field total integer
---@field loaded integer
---@field unloaded integer
---@field reset integer
---@field clear integer
---@field reload integer
---@field optional integer
---@field required integer
---@field entries table[]

local M = {}

return M
